name: ProtectionAPI
version: ${project.version}
main: com.haroldstudios.protectionapi.ProtectionAPI
api-version: 1.13
authors: [Harry0198]
description: This plugin allow
softdepend:
  - WorldGuard
  - WorldEdit
  - GriefPrevention
  - RedProtect
  - PlotSquared
  - Towny

commands:
  protection:
    description: Your description
    usage: /<command>